from __future__ import annotations
from dataclasses import dataclass
from typing import Dict, List, Literal

Stride = Literal["S", "T", "R", "I", "D", "E"]

STRIDE_LABELS: Dict[Stride, str] = {
    "S": "Spoofing (Falsificação de identidade)",
    "T": "Tampering (Adulteração)",
    "R": "Repudiation (Repúdio)",
    "I": "Information Disclosure (Exposição de informação)",
    "D": "Denial of Service (Negação de serviço)",
    "E": "Elevation of Privilege (Elevação de privilégio)",
}

@dataclass
class ThreatItem:
    stride: Stride
    title: str
    description: str
    mitigations: List[str]

KB: Dict[str, List[ThreatItem]] = {
    "user": [
        ThreatItem("S", "Uso de credenciais comprometidas",
                   "Atacante usa credenciais roubadas para acessar o sistema.",
                   ["MFA/2FA", "Política de senhas fortes", "Detecção de login anômalo"]),
        ThreatItem("R", "Ações sem rastreabilidade",
                   "Usuário nega ações por falta de trilha de auditoria.",
                   ["Logs de auditoria", "Carimbo de data/hora", "Correlação de eventos por usuário"]),
        ThreatItem("I", "Exposição via engenharia social",
                   "Vazamento de dados por phishing ou compartilhamento indevido.",
                   ["Treinamento", "DLP onde aplicável", "Princípio do menor privilégio"]),
    ],
    "identity_auth": [
        ThreatItem("S", "Sequestro/forja de tokens",
                   "Tokens de sessão/JWT podem ser roubados ou forjados.",
                   ["Assinatura e rotação de chaves", "Curto TTL + refresh seguro", "MFA", "TLS obrigatório"]),
        ThreatItem("T", "Adulteração de claims/perfis",
                   "Claims podem ser manipuladas se validação for fraca.",
                   ["Validação de assinatura", "Audience/issuer checks", "Scopes/roles no servidor"]),
        ThreatItem("R", "Falha de auditoria de autenticação",
                   "Sem logs de login, tentativas e mudanças de privilégios.",
                   ["Logs de autenticação", "Alertas de brute force", "Integração com SIEM"]),
        ThreatItem("D", "Brute force / credential stuffing",
                   "Ataques massivos de login degradam o serviço.",
                   ["Rate limit", "CAPTCHA/step-up auth", "Bloqueio progressivo", "WAF rules"]),
        ThreatItem("E", "Bypass de autorização",
                   "Permissões erradas permitem acesso elevado.",
                   ["RBAC/ABAC bem definido", "Least privilege", "Revisões periódicas de acesso"]),
    ],
    "api_gateway": [
        ThreatItem("S", "Chamadas sem autenticação",
                   "Endpoints expostos aceitam requests sem credenciais válidas.",
                   ["Auth obrigatória (OAuth2/JWT)", "mTLS para integrações", "Chaves/API keys com rotação"]),
        ThreatItem("T", "Manipulação de payload",
                   "Alteração de parâmetros/corpo pode explorar lógica de negócio.",
                   ["Validação de input (schema)", "Assinatura de requests quando aplicável", "Rejeitar campos desconhecidos"]),
        ThreatItem("R", "Falta de rastreio por request",
                   "Sem request-id e logs, não há atribuição de autoria.",
                   ["Request ID", "Logs estruturados", "Tracing distribuído"]),
        ThreatItem("I", "Headers/logs com dados sensíveis",
                   "Tokens/PII podem vazar via logs ou respostas.",
                   ["Redação de logs", "Política de erro sem detalhes", "Criptografia em trânsito"]),
        ThreatItem("D", "Ataque de volumetria",
                   "Flood de requests derruba API.",
                   ["Rate limit/quotas", "WAF", "Auto scaling", "Circuit breaker"]),
        ThreatItem("E", "Acesso indevido a rotas administrativas",
                   "Rotas internas acessadas por perfis comuns.",
                   ["Separar rotas admin", "Autorização por escopo", "Network segmentation"]),
    ],
    "waf_firewall": [
        ThreatItem("T", "Bypass de regras",
                   "Ataques ajustam payload para contornar assinaturas.",
                   ["Regras atualizadas", "Managed rules + custom", "Monitorar falsos negativos"]),
        ThreatItem("D", "DoS na borda",
                   "Ataques de L7 pressionam o WAF.",
                   ["Rate limit na borda", "Shield/Protection", "Caching quando aplicável"]),
        ThreatItem("I", "Exposição de endpoints por configuração",
                   "Regras permissivas deixam rotas sensíveis acessíveis.",
                   ["Hardening", "Allowlist quando possível", "Revisão periódica de regras"]),
    ],
    "cdn": [
        ThreatItem("I", "Cache de conteúdo sensível",
                   "Conteúdo com dados privados pode ser cacheado indevidamente.",
                   ["Cache-control correto", "Separar domínios", "Evitar cache para endpoints sensíveis"]),
        ThreatItem("T", "Injeção via conteúdo estático malicioso",
                   "Arquivos estáticos podem ser adulterados.",
                   ["Assinatura/integ. de artefatos", "Controle de versão", "SRI (web) quando aplicável"]),
        ThreatItem("D", "Amplificação de tráfego",
                   "CDN pode amplificar impacto se mal configurada.",
                   ["Rate limiting", "WAF na borda", "Proteção DDoS"]),
    ],
    "load_balancer": [
        ThreatItem("D", "Exaustão de conexões",
                   "Muitas conexões simultâneas derrubam o LB ou backends.",
                   ["Timeouts corretos", "Limites de conexão", "Auto scaling", "Health checks"]),
        ThreatItem("I", "TLS fraco / downgrade",
                   "Cifras fracas ou TLS mal configurado expõe dados.",
                   ["TLS moderno", "HSTS (web)", "mTLS interno quando necessário"]),
        ThreatItem("T", "Header spoofing (X-Forwarded-For)",
                   "IP de origem pode ser forjado sem validação.",
                   ["Confiar apenas em headers do LB", "Sanitização de headers", "Logs no LB"]),
    ],
    "app_service": [
        ThreatItem("S", "Service-to-service spoofing",
                   "Serviço malicioso finge ser outro serviço interno.",
                   ["mTLS", "Service identity", "Network policies"]),
        ThreatItem("T", "RCE / dependências vulneráveis",
                   "Código/dependências permitem execução remota ou alteração de dados.",
                   ["SAST/DAST", "SBOM", "Patch management", "Least privilege runtime"]),
        ThreatItem("R", "Ações sem auditoria de negócio",
                   "Operações críticas não têm trilha.",
                   ["Logs de negócio", "Auditoria por evento", "Imutabilidade de logs"]),
        ThreatItem("I", "Segredos expostos",
                   "Chaves/token em env/logs ou repositório.",
                   ["Secret manager", "Rotação", "Redação de logs", "CI checks"]),
        ThreatItem("D", "Exaustão de recursos",
                   "CPU/memória saturadas por payload pesado.",
                   ["Rate limit", "Limites de payload", "Auto scaling", "Fila assíncrona"]),
        ThreatItem("E", "Privilégios excessivos no runtime",
                   "Serviço com permissões além do necessário.",
                   ["IAM least privilege", "Separar roles", "Revisão de permissões"]),
    ],
    "database": [
        ThreatItem("T", "SQL injection / alteração de dados",
                   "Entrada não validada permite manipular queries e dados.",
                   ["ORM/prepared statements", "Validação de input", "WAF rules"]),
        ThreatItem("R", "Mudanças sem auditoria",
                   "Alterações sem trilha dificultam investigação.",
                   ["Auditoria (logs)", "Trilhas de alteração", "Controle de acesso por função"]),
        ThreatItem("I", "Vazamento de dados em repouso",
                   "Dados expostos por backups/snapshots ou acesso indevido.",
                   ["Criptografia at-rest", "KMS/Key Vault", "Privilégios mínimos", "Masking onde aplicável"]),
        ThreatItem("D", "Exaustão de conexões/locks",
                   "Muitas conexões ou queries lentas derrubam banco.",
                   ["Pool de conexões", "Índices", "Limites", "Read replicas"]),
        ThreatItem("E", "Escalada via credenciais do DB",
                   "Credenciais com permissões amplas permitem elevar acesso.",
                   ["Usuários separados por app", "Least privilege", "Rotação de senhas"]),
    ],
    "cache": [
        ThreatItem("I", "Cache poisoning / dados sensíveis",
                   "Dados errados/sensíveis podem vazar pelo cache.",
                   ["Chaves de cache bem definidas", "Evitar cache de PII", "TTL adequado"]),
        ThreatItem("D", "Eviction / cache stampede",
                   "Explosão de misses causa sobrecarga no backend.",
                   ["TTL com jitter", "Locking/Singleflight", "Warmup"]),
        ThreatItem("E", "Acesso administrativo ao cache",
                   "Painéis/portas abertas permitem controle do cache.",
                   ["Rede privada", "Auth", "Segurança por grupo/NSG"]),
    ],
    "storage": [
        ThreatItem("I", "Buckets/containers públicos",
                   "Armazenamento exposto por política incorreta.",
                   ["Bloquear acesso público", "Políticas mínimas", "Revisão de ACLs"]),
        ThreatItem("T", "Upload malicioso",
                   "Arquivos podem conter malware ou scripts.",
                   ["Antivírus/scan", "Validação de tipo", "Assinatura de uploads"]),
        ThreatItem("R", "Sem trilha de acesso a objetos",
                   "Sem logs não é possível rastrear downloads/alterações.",
                   ["Logs de acesso", "Versionamento", "Imutabilidade (quando necessário)"]),
        ThreatItem("D", "Abuso de armazenamento",
                   "Crescimento descontrolado gera custo/indisponibilidade.",
                   ["Quotas", "Lifecycle policies", "Alertas de uso"]),
    ],
    "monitoring_logging": [
        ThreatItem("T", "Adulteração de logs",
                   "Atacante tenta apagar/alterar trilhas.",
                   ["Logs imutáveis", "Write-once/retention", "Acesso restrito"]),
        ThreatItem("I", "Logs com dados sensíveis",
                   "PII/segredos em logs.",
                   ["Redação", "Política de logging", "Scrubbing"]),
        ThreatItem("D", "Explosão de logs/telemetria",
                   "Logging excessivo derruba performance/custo.",
                   ["Rate limit de logs", "Sampling", "Alertas de volume"]),
    ]
}

